packages:
  - plugins/*
  - scripts/dsh-bootstrap

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: true

onlyBuiltDependencies:
  - '@deepseek-ai/dsh-subprocess-local'
  - '@google/genai'
  - esbuild
  - koffi
  - node-pty
  - protobufjs
