# BEGIN DSH-REMOTE MANAGED
map $http_upgrade $dsh_remote_connection {
    default upgrade;
    '' close;
}

upstream dsh_remote_gateway {
    server unix:__SOCKET_CONTAINER_PATH__;
    server 127.0.0.1:18081 backup;
    keepalive 8;
}

server {
    listen 80;
    server_name __DOMAIN__;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        __HTTP_ACTION__
    }
}

__HTTPS_SERVER__
# END DSH-REMOTE MANAGED
